# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdhDwkigmic00_etRz_1H5tT0-EDYHor
"""

import pandas as pd
baza={
    "FISH":[ "Aliyeva Rano", "Aliyev Ali", "Sobirov Nodir", "Komilova Aziza", "Dehqonov Alisher", "Bakirov Aziz", "Aliyeva Rano", "Aliyev Ali", "Sobirov Nodir", "Komilova Aziza"],
    "Yoshi":[ "15", "17", "14", "12", "19", "15", "17", "14", "12", "19", ],
    "Maktabi":[ "2-maktab", "24-maktab", "42-maktab", "27-maktab", "41-maktab", "22-maktab", "14-maktab", "16-maktab", "43-maktab", "13-maktab" ],
    "Jinsi":[ "Qiz bola", "O'g'il bola", "O'g'il bola", "Qiz bola", "O'g'il bola", "O'g'il bola", "Qiz bola", "O'g'il bola", "O'g'il bola", "Qiz bola"],
    "Manzili":[ "Farg'ona shahar", "Andijon shahar", "Namangan shahar", "Farg'ona shahar", "Andijon shahar", "Namangan shahar", "Farg'ona shahar", "Andijon shahar", "Namangan shahar", "Toshkent shahar" ],

}
db=pd.DataFrame(baza)
print(db)

filtr=db[db["Jinsi"]=="O'g'il bola"]
print(filtr)

filtr=db[db["Jinsi"]=="Qiz bola"]
print(filtr)

